"use strict";
let car = "Subaru";
console.log("Is car === 'Subaru' ?| I predict :  true");
console.log(car == "Subaru");
console.log("Is car == 'honda' ?| I predict : false");
console.log(car == "honda");
let numeric = 89;
console.log(" Is numeric === 89 | I predict: true");
console.log(numeric == 89);
console.log("Is numeric === 57 | I predict: False");
console.log(numeric == 57);
let fruit = "orange";
console.log("Is fruit === 'banana' | I predict : false  ");
console.log(fruit == "banana");
console.log("Is fruit === 'orange' | I predict : true  ");
console.log(fruit == "orange");
let bike = " Kawasaki";
console.log("Is bike == 'Kawasaki' ? | I predict : true ");
console.log(bike == "Kawasaki");
console.log(" Is bike === 'Hayabusa' ? | I predict : false ");
console.log(bike == "Hayabusa");
let house = " flat";
console.log("Is house == 'flat' | I predict true");
console.log(house == "flat");
console.log(" Is house == 'banglow' | I predict false");
console.log(house == "banglow");
let food = "Biryani";
console.log(" Is food == 'Biryani' | I predict true");
console.log(food == "Biryani");
console.log(" Is food =='Karhai' | I predict false ");
console.log(food == "Karhai");
